### ISSUE TITLE
Errors after installing under Ubuntu 20.04

### ISSUE THREAD

**Issue by clopmz** [stricaud/sightingdb#8]
After compiling sightingdb in a Ubuntu 20.04 hosts and trying tor run it, the following errors appears:

root@ubutest:/tmp# sightingdb
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Log4rs(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/main.rs:535:5
stack backtrace:
   0:     0x55ef55f71894 - backtrace::backtrace::libunwind::trace::ha716b483344307d4
                               at /usr/src/rustc-1.43.0/vendor/backtrace/src/backtrace/libunwind.rs:86
   1:     0x55ef55f71894 - backtrace::backtrace::trace_unsynchronized::h73191aaca03de050
                               at /usr/src/rustc-1.43.0/vendor/backtrace/src/backtrace/mod.rs:66
   2:     0x55ef55f71894 - std::sys_common::backtrace::_print_fmt::h515542a6f0149e5c
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x55ef55f71894 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbd3babec5fee3351
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55ef55f924bc - core::fmt::write::ha5eb378c8b683563
                               at src/libcore/fmt/mod.rs:1063
   5:     0x55ef55f715d7 - std::io::Write::write_fmt::h7525b2825ed7383d
                               at src/libstd/io/mod.rs:1426
   6:     0x55ef55f62e95 - std::sys_common::backtrace::_print::hfec26b72b492a55c
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55ef55f62e95 - std::sys_common::backtrace::print::h05570acc7a135366
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55ef55f62e95 - std::panicking::default_hook::{{closure}}::h9278410915688d73
                               at src/libstd/panicking.rs:204
   9:     0x55ef55f62b86 - std::panicking::default_hook::hd3a187a77f7140a0
                               at src/libstd/panicking.rs:224
  10:     0x55ef55f634e2 - std::panicking::rust_panic_with_hook::hb04c51c9d1a7c747
                               at src/libstd/panicking.rs:470
  11:     0x55ef55f630cb - rust_begin_unwind
                               at src/libstd/panicking.rs:378
  12:     0x55ef55f91cd1 - core::panicking::panic_fmt::h2e8e792413b965d4
                               at src/libcore/panicking.rs:85
  13:     0x55ef55f91d63 - core::result::unwrap_failed::hd3b7fabe5a010559
                               at src/libcore/result.rs:1222
  14:     0x55ef55606323 - core::result::Result<T,E>::unwrap::h75bfb797ae9b93ac
                               at /usr/src/rustc-1.43.0/src/libcore/result.rs:1003
  15:     0x55ef5559e287 - sightingdb::main::h4857ba9e72ccc075
                               at src/main.rs:535
  16:     0x55ef555d338b - std::rt::lang_start::{{closure}}::h4cb16a827515e9df
                               at /usr/src/rustc-1.43.0/src/libstd/rt.rs:67
  17:     0x55ef55f62fb3 - std::rt::lang_start_internal::{{closure}}::ha76aba2c161a67a4
                               at src/libstd/rt.rs:52
  18:     0x55ef55f62fb3 - std::panicking::try::do_call::hb203df4ff1d5ed94
                               at src/libstd/panicking.rs:303
  19:     0x55ef55f77827 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  20:     0x55ef55f6455c - std::panicking::try::h785999c549ea777b
                               at src/libstd/panicking.rs:281
  21:     0x55ef55f6455c - std::panic::catch_unwind::hbc99eda2c23b3349
                               at src/libstd/panic.rs:394
  22:     0x55ef55f6455c - std::rt::lang_start_internal::h58283c2b5ed737c9
                               at src/libstd/rt.rs:51
  23:     0x55ef555d3367 - std::rt::lang_start::h0779972fdeba89b2
                               at /usr/src/rustc-1.43.0/src/libstd/rt.rs:67
  24:     0x55ef555a0c3a - main
  25:     0x7f2c9f8c20b3 - __libc_start_main
  26:     0x55ef555381be - _start
  27:                0x0 - <unknown>

**Comment by ch4r13** [comment]
I have same problem, after few tries continued to next error
```
root@ubu-srv-101:/home/user/sightingdb# ./target/debug/sightingdb
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Cannot locate sightingdb.conf in neither from the -c flag, /etc/sightingdb or ~/.sightingdb/"', src/main.rs:551:63
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
root@ubu-srv-101:/home/user/sightingdb#

```
